[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "/Users/davidmiles/git/probe-rs/target/debug/probe-rs run --chip RP235x"
#runner = "picotool load -u -v -x -t elf"

[build]
#target = "thumbv6m-none-eabi"        # Cortex-M0 and Cortex-M0+
target = "thumbv8m.main-none-eabihf"

[env]
DEFMT_LOG = "info"
